# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# Oppdater med riktig informasjon
id: ehin.fhir.hackaton.aidn.no
canonical: http://aidn.no/ehin/fhir/hackaton
name: EHIN FHIR Hackaton - Aidn
title: "EHIN FHIR Hackaton - Aidn."
description: Test av implementasjonsguide EHIN FHIR Hackaton - Aidn
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#NO "Norway"
# Oppdater navn og URL til din organisasjon
publisher:
  name: Aidn
  url: https://www.aidn.no
dependencies:
  hl7.fhir.no.basis: 2.2.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  TOC: toc.html
